#!/bin/sh

# 4
echo "postinst..."

chown root:wheel /usr/bin/kratos-ios-helper
chown root:wheel /Library/LaunchDaemons/com.test.go-kratos.plist

chmod 755 /usr/bin/kratos-ios-helper
ldid -S/Library/LaunchDaemons/com.test.go-kratos.plist /usr/bin/kratos-ios-helper


launchctl load -w /Library/LaunchDaemons/com.test.go-kratos.plist
