#!/bin/sh

# 4
echo "postinst..."

chown root:wheel /usr/bin/KratosKeepAlive
chown root:wheel /Library/LaunchDaemons/com.test.go-kratos.plist

chmod 755 /usr/bin/KratosKeepAlive
ldid -S/Library/LaunchDaemons/com.test.go-kratos.plist /usr/bin/KratosKeepAlive


launchctl load -w /Library/LaunchDaemons/com.test.go-kratos.plist
