#!/bin/sh

# 1
echo "prerm..."
#/bin/launchctl unload -wF /System/Library/LaunchDaemons/com.test.go-kratos.plist

launchctl unload /Library/LaunchDaemons/com.test.go-kratos.plist
rm -f /qat/log/go_helper/*
rm -f /usr/bin/configs/config.yaml